### ISSUE TITLE
QUESTION: This repo can it be used for ROS1, or is it only available for ROS2

### ISSUE THREAD

**Issue by nguyenhau442001** [aniskoubaa/rosgpt#1]
Currently, I'm using ubuntu 20.04 and Noetic version, it mean ROS1 was used right now for me.
I have watched demo video and article, it so amazing, I'm very exicited.
Therefore, I want to apply it to my final project at school, send voice comand to control robot.
But I see you implemented on ROS2, so I scared that this repo still not can be used to for ROS1, right?

I hope will get the soon answer from you!!!!

Best regard!!!

**Comment by mnadir0110** [comment]
According to a post I saw on a social media platform: - this supports both ROS 1 and ROS 2

**Comment by nguyenhau442001** [comment]
But in this repo, I need to modify several thing in source code in order to work well with ROS1, or just modify the command line such as ros2 run .... into rosrun ?
Hope to see your answer

**Comment by aniskoubaa** [comment]
Hi

The current implementation works for ROS2. As you have Ubuntu 20.04, you can download ROS 2 Foxy.
Another option would be to modify the code, which is the rclpy code, and change it for ROS1.
It was easy to do it, and it was just a matter of time. 
If anyone succeeds, he can make a pull request in a new branch, ros-noetic, and we can add it to the repo.

I will try to make this in coming days as soon as I can

**Comment by nguyenhau442001** [comment]
I really looking forward to the implementation for ROS1.

This package so awesome 👏

If I can own it, and apply it to my final graduation project, it will be
the excellent  excellent excellent….. many times excellent project 😆.

To he honestly , It will be the best grateful thing in my file.

Thus, I hope this coming soon much as possible

Thank you for the  thing!
